Models/Employee.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    [BindProperties(SupportsGet = true)]
    public class Employee
    {
        [Required]
        public string? EmployeeID { get; set; }

        [Required]
        [StringLength(10, MinimumLength = 3)]
        public string? Fname { get; set; }

        public string? RoleName { get; set; }
        public string? PhoneNumber { get; set; }
        public string? Branch_ID { get; set; }
    }
}


Pages/Admin.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data;
using WebApplication1.Models;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System.Xml.Linq;

namespace WebApplication1.Pages
{
    [BindProperties(SupportsGet = true)]

    public class AdminModel : PageModel
    {

        private readonly ILogger<AdminModel> _logger;
        public DB db { get; set; }
        public DataTable EmployeeDataTable { get; set; }

        public Employee emplist { get; set; }

        public AdminModel(ILogger<AdminModel> logger, DB db)
        {
            _logger = logger;
            this.db = db;
        }

        public void OnGet()
        {
            EmployeeDataTable = db.ReadTable("Employee");
        }


        [BindProperty]
        public string EmployeeID { get; set; }

        [BindProperty]
        public string Fname { get; set; }

        [BindProperty]
        public string PhoneNumber { get; set; }

        [BindProperty]
        public string Email { get; set; }


        [BindProperty]
        public string ManagerID { get; set; }

        [BindProperty]
        public string ManagerName { get; set; }

        [BindProperty]
        public string ManagerEmail { get; set; }

        [BindProperty]
        public string ManagerPhoneNumber { get; set; }



        public IActionResult OnPost()
            {
                string connection = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=StockifyUpdated;Data Source=DESKTOP-9IHIA03";
                SqlConnection con = new SqlConnection(connection);
                string query = "";

                SqlCommand cmd = new SqlCommand(query, con);

                if(Request.Form["adminButton"].Count > 0)
                {
                    // Admin button was pressed
                    query = "insert into Employee(Fname, EmployeeID, RoleName, PhoneNumber, Email) values(@Fname, @EmployeeID, @RoleName, @PhoneNumber, @Email)";
                    cmd.Parameters.AddWithValue("@Fname", Fname);
                    cmd.Parameters.AddWithValue("@EmployeeID", EmployeeID);
                    cmd.Parameters.AddWithValue("@RoleName", "Admin");
                    cmd.Parameters.AddWithValue("@PhoneNumber", PhoneNumber);
                    cmd.Parameters.AddWithValue("@Email", Email);
                }
                else
                {
                    // Manager button was pressed
                    query = "insert into Employee(Fname, EmployeeID, RoleName, PhoneNumber, Email) values(@ManagerName, @ManagerID, @RoleName, @ManagerPhoneNumber, @ManagerEmail)";
                    cmd.Parameters.AddWithValue("@ManagerName", ManagerName);
                    cmd.Parameters.AddWithValue("@ManagerID", ManagerID);
                    cmd.Parameters.AddWithValue("@RoleName", "Manager");
                    cmd.Parameters.AddWithValue("@ManagerPhoneNumber", ManagerPhoneNumber);
                    cmd.Parameters.AddWithValue("@ManagerEmail", ManagerEmail);
                }

                cmd.CommandText = query;
                Console.Write(query);
                string res = "";

                try
                {
                    con.Open();
                    res = cmd.ExecuteNonQuery().ToString();
                }
                catch (SqlException err)
                {
                    res = err.Message;
                }
                finally
                {
                    con.Close();
                }

                return RedirectToPage("/Admin");
            }
    }
}

Pages/ChangePassword.cshtml.cs
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.ComponentModel.DataAnnotations;

public class ChangePasswordModel : PageModel
{
    private readonly IConfiguration _configuration;

    [BindProperty]
    public string Username { get; set; }

    [BindProperty]
    [StringLength(8, ErrorMessage = "The {0} must be at least {1} characters long.", MinimumLength = 8)]
    public string NewPassword { get; set; }

    [BindProperty]
    public string ConfirmNewPassword { get; set; }

    [BindProperty]
    public string Answer { get; set; }

    [BindProperty]
    public string Question { get; set; }

    public ChangePasswordModel(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public IActionResult OnPost()
    {
        try
        {
            if (ModelState.IsValid)
            {
                string connectionString = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=StockifyUpdated;Data Source=DESKTOP-9IHIA03";

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    if (!IsUserValid(connection, Username, Answer, Question))
                    {
                        ModelState.AddModelError("Invalid", "Invalid username, answer, or question.");
                        return Page();
                    } 

                    if (NewPassword != ConfirmNewPassword)
                    {
                        ModelState.AddModelError("ConfirmNewPassword", "The new password and confirmation do not match.");
                        return Page();
                    }

                    string hashedNewPassword = HashPassword(NewPassword);

                    if (UpdatePassword(connection, Username, hashedNewPassword))
                    {
                        return RedirectToPage("/SignIn"); 
                    }
                }
            }
        }
        catch (SqlException)
        {
            ModelState.AddModelError(string.Empty, "An error occurred while processing your request. Please try again.");
        }

        return Page();
    }

    private bool IsUserValid(SqlConnection connection, string username, string answer, string question)
        {
            // Query for answer 
            string getAnswerQuery = "SELECT Answer FROM Signups WHERE Username = @Username";

            using (SqlCommand answerCommand = new SqlCommand(getAnswerQuery, connection))
            {
                answerCommand.Parameters.AddWithValue("@Username", username);
                object result1 = answerCommand.ExecuteScalar();

                if (result1 != null)
                {
                    string storedAnswer = result1.ToString();

                    if (storedAnswer == answer)
                    {
                        // Query for answer
                        string getQuestionQuery = "SELECT Question FROM Signups WHERE Username = @Username";

                        using (SqlCommand questionCommand = new SqlCommand(getQuestionQuery, connection))
                        {
                            questionCommand.Parameters.AddWithValue("@Username", username);
                            object result2 = questionCommand.ExecuteScalar();

                            if (result2 != null)
                            {
                                string storedQuestion = result2.ToString();

                                return storedQuestion == question;
                            }
                        }
                    }
                }

                return false; 
            }
        }





    private bool UpdatePassword(SqlConnection connection, string username, string hashedNewPassword)
    {
        string updateQuery = "UPDATE Signups SET Password = @Password WHERE Username = @Username";

        using (SqlCommand command = new SqlCommand(updateQuery, connection))
        {
            command.Parameters.AddWithValue("@Username", username);
            command.Parameters.AddWithValue("@Password", hashedNewPassword);

            int rowsAffected = command.ExecuteNonQuery();

            return rowsAffected > 0;
        }
    }


        private string HashPassword(string password)
            {
                byte[] salt = new byte[16];
                using (var rng = RandomNumberGenerator.Create())
                {
                    rng.GetBytes(salt);
                }

                string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: password,
                    salt: salt,
                    prf: KeyDerivationPrf.HMACSHA256,
                    iterationCount: 10000,
                    numBytesRequested: 256 / 8));

                return $"{Convert.ToBase64String(salt)}:{hashed}";
            }
}

Pages/Devices.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class DevicesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Employees.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data;
using WebApplication1.Models;
using System.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System.Xml.Linq;

namespace WebApplication1.Pages
{
    [BindProperties(SupportsGet = true)]

    public class EmployeesModel : PageModel
    {

        private readonly ILogger<EmployeesModel> _logger;
        public DB db { get; set; }
        public DataTable EmployeeDataTable { get; set; }

        public Employee emplist { get; set; }

        public EmployeesModel(ILogger<EmployeesModel> logger, DB db)
        {
            _logger = logger;
            this.db = db;
        }

        public void OnGet()
        {
            EmployeeDataTable = db.ReadTable("Employee");
        }


        [BindProperty]
        public string EmployeeID { get; set; }

        [BindProperty]
        public string Fname { get; set; }

        [BindProperty]
        public string RoleName { get; set; }

        [BindProperty]
        public string PhoneNumber { get; set; }
        [BindProperty]
        public string Branch_ID { get; set; }



        public IActionResult OnPostInsert()
        {

            string connection = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=StockifyUpdated;Data Source=DESKTOP-9IHIA03";
            SqlConnection con = new SqlConnection(connection);
            string query = "insert into Employee(Fname, EmployeeID, RoleName, PhoneNumber, Branch_ID) values(@Fname, @EmployeeID,@RoleName,@PhoneNumber,@Branch_ID)";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@Fname", Fname);
            cmd.Parameters.AddWithValue("@EmployeeID", int.Parse(EmployeeID));
            cmd.Parameters.AddWithValue("@RoleName", RoleName);
            cmd.Parameters.AddWithValue("@PhoneNumber", PhoneNumber);
            cmd.Parameters.AddWithValue("@Branch_ID", int.Parse(Branch_ID));
            Console.Write(query);
            string res = "";
            try
            {
                con.Open();
                res = cmd.ExecuteNonQuery().ToString();

            }
            catch (SqlException err)
            {
                res = err.Message;
            }
            finally
            {

                con.Close();
            }
            return RedirectToPage("/Employees");            
        }
    }
}


Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/SignUp.cshtml.cs
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.ComponentModel.DataAnnotations;

public class SignUpModel : PageModel
{
    private readonly IConfiguration _configuration;

    [BindProperty]
    public string Username { get; set; }

    [BindProperty]
    [StringLength(8, ErrorMessage = "The {0} must be at least {1} characters long.", MinimumLength = 8)]
    public string Password { get; set; }

    [BindProperty]
    public string ConfirmPassword { get; set; }

    [BindProperty]
    public string ID { get; set; }

    [BindProperty]
    public string Answer { get; set; }

    [BindProperty]
    public string Question { get; set; }

    public SignUpModel(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public IActionResult OnPost()
    {
        try
        {
            if (ModelState.IsValid)
            {
                if (Password != ConfirmPassword)
                {
                    ModelState.AddModelError("ConfirmPassword", "The password and confirmation password do not match.");
                    return Page();
                }

                string connectionString = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=StockifyUpdated;Data Source=DESKTOP-9IHIA03";

                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    if (IsIdAlreadyExists(connection, ID))
                    {
                        ModelState.AddModelError("ID", "Error with ID. This ID already exists.");
                        return Page();
                    }

                    string hashedPassword = HashPassword(Password);

                    string insertQuery = "INSERT INTO Signups (Username, Password, Employee_id, Answer, Question) VALUES (@Username, @Password, @ID, @Answer, @Question)";

                    using (SqlCommand command = new SqlCommand(insertQuery, connection))
                    {
                        command.Parameters.AddWithValue("@Username", Username);
                        command.Parameters.AddWithValue("@Password", hashedPassword);
                        command.Parameters.AddWithValue("@ID", ID);
                        command.Parameters.AddWithValue("@Answer", Answer);
                        command.Parameters.AddWithValue("@Question", Question);

                        int rowsAffected = command.ExecuteNonQuery();

                        if (rowsAffected > 0)
                        {
                            return RedirectToPage("/SignIn");
                        }
                    }
                }
            }
        }
        catch (SqlException)
        {
            ModelState.AddModelError(string.Empty, "An error occurred while processing your request. Please try again.");
        }

        return Page();
    }

    private bool IsIdAlreadyExists(SqlConnection connection, string id)
    {
        string checkQuery = "SELECT COUNT(*) FROM Signups WHERE Employee_id = @ID";

        using (SqlCommand command = new SqlCommand(checkQuery, connection))
        {
            command.Parameters.AddWithValue("@ID", id);

            int count = (int)command.ExecuteScalar();

            return count > 0;
        }
    }

    private string HashPassword(string password)
    {
        byte[] salt = new byte[16];
        using (var rng = RandomNumberGenerator.Create())
        {
            rng.GetBytes(salt);
        }

        string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
            password: password,
            salt: salt,
            prf: KeyDerivationPrf.HMACSHA256,
            iterationCount: 10000,
            numBytesRequested: 256 / 8));

        return $"{Convert.ToBase64String(salt)}:{hashed}";
    }
}

Pages/home.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class homeModel : PageModel
    {
        private readonly ILogger<homeModel> _logger;

        public homeModel(ILogger<homeModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/suppliers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication1.Pages
{
    public class suppliersModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Admin.cshtml
@page
@using System.Data;
@model WebApplication1.Pages.AdminModel
@{
    Layout = "";
    ViewData["Title"] = "Stockify";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta " content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        body {
            margin-top: 70px;
        }

        .navbar {
            background-color: #343a40;
        }

        .navbar-brand img {
            filter: brightness(0) invert(1);
        }

        .modal-header {
            background-color: #007bff;
            color: #fff;
        }

        .modal-footer {
            background-color: #f8f9fa;
        }

        /* Table styles */
        .table th, .table td {
            text-align: center;
        }

        .table thead th {
            background-color: #007bff;
            color: #fff;
        }

        .table-hover tbody tr:hover {
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" asp-page="/Admin">
            <img src="~/static/Stock.png" alt="Logo" height="50" width="50">
        </a>

        <!-- Navbar toggler button for responsive design -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links with centered "ADMIN" using Bootstrap grid -->
        <div class="container-fluid d-flex justify-content-center">
            <span class="nav-link font-weight-bold text-white">ADMIN</span>
        </div>
    </nav>

    <!-- Admins Table -->
    <div class="container mt-5">
        <h2 class="text-primary mb-4">Admins Table</h2>
        <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#adminModal">
            Add Admin
        </button>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th> PhoneNumber</th>
                </tr>
            </thead>
             <tbody>
            @foreach (DataRow row in Model.EmployeeDataTable.Rows)
            {
                var roleName = row["RoleName"].ToString();

                // Check if the role is equal to "Admin" before displaying the row
                if (roleName.Equals("Admin", StringComparison.OrdinalIgnoreCase))
                {
                    <tr>
                        <td>@row["EmployeeID"]</td>
                        <td>@row["Fname"]</td>
                        <td>@row["Email"]</td>
                        <td>@row["PhoneNumber"]</td>
                    </tr>
                }
            }
        </tbody>
        </table>

        <!-- Admins Modal -->
    <div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="adminModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="adminModalLabel">Add Admin</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Add Admin Form Content -->
                <form method="post" asp-page-handler="Insert" id="employeeForm">
                    <input type="hidden" id="employeeIdHidden" name="employeeIdHidden">
                    
                    <div class="form-group">
                        <label for="adminID">ID:</label>
                        <input type="text" class="form-control"  placeholder="Enter ID" id="adminID" asp-for="@Model.EmployeeID" required>
                    </div>
                    <div class="form-group">
                        <label for="adminName">Name:</label>
                        <input type="text" class="form-control"  placeholder="Enter name" id="adminName" asp-for="@Model.Fname" required>
                    </div>
                    <div class="form-group">
                        <label for="adminEmail">Email:</label>
                        <input type="text" class="form-control" placeholder="Enter email" id="adminEmail" asp-for="@Model.Email" required>
                    </div>
                    <div class="form-group">
                        <label for="adminPhone">Phone Number:</label>
                        <input type="text" class="form-control" placeholder="Enter Phone Number" id="adminPhone" asp-for="@Model.PhoneNumber" required>
                    </div>
                    <!-- Add more form fields as needed -->
                    <button type="submit" class="btn btn-primary" name="adminButton" onclick="saveEmployee()">Save changes</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

    <!-- Managers Table -->
     <div class="container mt-5">
        <h2 class="text-success mb-4">Managers Table</h2>
        <button type="button" class="btn btn-success mb-3" data-toggle="modal" data-target="#managerModal">
            Add Manager
        </button>
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>PhoneNumber</th>
                </tr>
            </thead>
            <tbody>
            @foreach (DataRow row in Model.EmployeeDataTable.Rows)
            {
                var roleName = row["RoleName"].ToString();

                // Check if the role is equal to "Admin" before displaying the row
                if (roleName.Equals("Manager", StringComparison.OrdinalIgnoreCase))
                {
                    <tr>
                        <td>@row["EmployeeID"]</td>
                        <td>@row["Fname"]</td>
                        <td>@row["Email"]</td>
                        <td>@row["PhoneNumber"]</td>
                    </tr>
                }
            }
        </tbody>
        </table>

        <!-- Managers Modal -->
         <div class="modal fade" id="managerModal" tabindex="-1" role="dialog" aria-labelledby="managerModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="managerModalLabel">Add Manager</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Add Manager Form Content -->
                    <form method="post" asp-page-handler="Insert" id="employeeForm"> 
                        <input type="hidden" id="employeeIdHidden" name="employeeIdHidden">
                        <div class="form-group">
                            <label for="managerID">ID:</label>
                            <input type="text" class="form-control" placeholder="Enter ID" id="managerID" asp-for="@Model.ManagerID" required>
                        </div>
                        <div class="form-group">
                            <label for="managerName">Name:</label>
                            <input type="text" class="form-control" placeholder="Enter name" id="managerName" asp-for="@Model.ManagerName" required>
                        </div>
                        <div class="form-group">
                            <label for="managerEmail">Email:</label>
                            <input type="text" class="form-control" placeholder="Enter email" id="managerEmail" asp-for="@Model.ManagerEmail" required>
                        </div>
                        <div class="form-group">
                            <label for="managerPhone">Phone Number:</label>
                            <input type="text" class="form-control" placeholder="Enter Phone Number" id="managerPhone" asp-for="@Model.ManagerPhoneNumber" required>
                        </div>
                        <!-- Add more form fields as needed -->
                        <button type="submit" class="btn btn-primary" onclick="saveEmployee()">Save changes</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JavaScript dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <!-- Additional scripts for each modal, if needed -->
    <script>
    var editingRow;

    function deleteRow(button) {
        // Find the closest 'tr' element and remove it
        var row = button.closest('tr');
        row.remove();
    }

    function editRow(button) {
        editingRow = button.closest('tr');

        // Get the data from the row
        var employeeId = editingRow.cells[0].innerHTML;
        var name = editingRow.cells[1].innerHTML;
        var worksAs = editingRow.cells[2].innerHTML;
        var phoneNumber = editingRow.cells[3].innerHTML;
        var branch = editingRow.cells[4].innerHTML;

        // Set the values in the modal form
        document.getElementById('employeeIdHidden').value = employeeId;
        document.getElementById('employeeId').value = employeeId;
        document.getElementById('name').value = name;
        document.getElementById('worksAs').value = worksAs;
        document.getElementById('phoneNumber').value = phoneNumber;
        document.getElementById('branch').value = branch;

        // Open the modal
        $('#AddEditEmployee').modal('show');
    }

    function resetForm() {
        document.getElementById('employeeIdHidden').value = '';
        document.getElementById('employeeId').value = '';
        document.getElementById('name').value = '';
        document.getElementById('worksAs').value = '';
        document.getElementById('phoneNumber').value = '';
        document.getElementById('branch').value = '';

    }

    function saveEmployee() {
        console.log("maryam here in save employee");
        // Retrieve input values from the form
        var employeeId = document.getElementById('employeeId').value;
        var name = document.getElementById('name').value;
        var worksAs = document.getElementById('worksAs').value;
        var phoneNumber = document.getElementById('phoneNumber').value;
        var branch = document.getElementById('branch').value;

        if (editingRow) {
            // Update the existing row if in edit mode
            editingRow.cells[0].innerHTML = employeeId;
            editingRow.cells[1].innerHTML = name;
            editingRow.cells[2].innerHTML = worksAs;
            editingRow.cells[3].innerHTML = phoneNumber;
            editingRow.cells[4].innerHTML = branch;
            editingRow = null; // Reset editing mode
        } else {
            // Create a new row if not in edit mode
            var tbody = document.querySelector('tbody');
            var newRow = tbody.insertRow();

            var data = [employeeId, name, worksAs, phoneNumber, branch];
            for (var i = 0; i < data.length; i++) {
                var cell = newRow.insertCell(i);
                cell.innerHTML = data[i];

            }

            var actionsCell = newRow.insertCell(data.length);
            actionsCell.innerHTML = '<button class="btn btn-danger" onclick="deleteRow(this)">Delete</button>' +
                '<button class="btn btn-primary ml-2" onclick="editRow(this)">Edit</button>';
            document.getElementById('employeeIdHidden').value = '';
        }
        var employee = {
            EmployeeId: employeeId,
            Name: name,
            WorksAs: worksAs,
            PhoneNumber: phoneNumber,
            Branch: branch
        };



        // Close the modal
        $('#AddEditEmployee').modal('hide');



    }
</script>
</body>
</html>

Pages/home.cshtml
@page
@model homeModel

@{
    
    Layout = TempData["Layout"] as string ?? "_Layout";
    ViewData["Title"] = "Stockify";
   
}



    <div class="container">
        <div class="jumbotron mt-5">
            <h1 class="display-4">Welcome to Stockify!</h1>
            <p class="lead">Retail Management was never easier!.</p>

        </div>
    </div>




